linters:
  enable:
    - revive 
    - ifshort 
    - gocritic 
    - dogsled 
    - gosec 
    - misspell 
    - goconst 
    - goconst 
    - noctx 
    - godot
    - goimports
    - nakedret
    - exportloopref
